services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo17:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    # command: odoo -d odoo_db -i base --db_user=odoo --db_password=odoo --db_host=db # remove '-i base' after the first run
    command: odoo -d odoo_db -u todo_list_module --dev=xml --db_user=odoo --db_password=odoo --db_host=db

volumes:
  odoo-db-data:
  odoo-web-data:
