{
    'name': 'Todo List',
    'version': '1.0.0',
    'summary': 'Manage your todo lists',
    'category': 'To-Do',
    'author': 'TOEYJIRA',
    'website': 'https://github.com/TOEYJIRAKID/odoo-docker-dev',
    'depends': ['base'],
    'data': [
        'security/todo_security.xml',
        'security/ir.model.access.csv',
        'data/todo_tags_data.xml',
        'views/todo_list_views.xml',
        'views/menu_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}